-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.19.0.7314
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for essentialmode
DROP DATABASE IF EXISTS `essentialmode`;
CREATE DATABASE IF NOT EXISTS `essentialmode` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE `essentialmode`;

-- Dumping structure for table essentialmode.items
DROP TABLE IF EXISTS `items`;
CREATE TABLE IF NOT EXISTS `items` (
  `name` varchar(50) NOT NULL,
  `label` varchar(50) NOT NULL,
  `limit` int(11) NOT NULL DEFAULT -1,
  `rare` tinyint(1) NOT NULL DEFAULT 0,
  `can_remove` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table essentialmode.items: ~238 rows (approximately)
REPLACE INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('aard', 'Aard', 30, 0, 1),
	('abporteghal', 'Ab Porteghal', 10, 0, 1),
	('air_freshener_pine', 'Air Freshener Pine', 10, 0, 1),
	('alive_chicken', 'ElÃ¤vÃ¤ kana', 20, 0, 1),
	('armor', 'Armor', -1, 0, 1),
	('bakingpowder', 'Baking Powder', 30, 0, 1),
	('bandage', 'Bandage', 20, 0, 1),
	('bastani', 'Bastani', 10, 0, 1),
	('beer', 'Beer', 30, 0, 1),
	('berenj_sushi', 'Berenj Sushi', 30, 0, 1),
	('blackmoney', 'Black Money', -1, 1, 1),
	('blowpipe', 'Chalumeaux', 10, 0, 1),
	('blowtorch', 'Blowtorch', -1, 0, 1),
	('bobal_tea_matcha', 'Bobal Tea Matcha', 10, 0, 1),
	('bobal_tea_tamshak', 'Bobal Tea Tamshak', 10, 0, 1),
	('boba_milk_tea_caramel', 'Boba Milk Tea Caramel', 10, 0, 1),
	('boba_milk_tea_matcha', 'Boba Milk Tea Matcha', 10, 0, 1),
	('bread', 'Bread', -1, 0, 1),
	('breathalyzer', 'Test Alchol', 10, 0, 1),
	('bubbletetotfarangi', 'Bubblete Totfarangi', 10, 0, 1),
	('cakebastani', 'Cake Bastani', 10, 0, 1),
	('cakebastanivanili', 'Cake Bastani Vanili', 10, 0, 1),
	('caketotfarangi', 'Cake Totfarangi', 10, 0, 1),
	('cake_bastani_vanili', 'Cake Bastani Vanili', 10, 0, 1),
	('cake_limoii', 'Cake Limoii', 10, 0, 1),
	('calzone', 'Calzone', 10, 0, 1),
	('cannabis', 'Hashish', 50, 0, 1),
	('carokit', 'Kit carosserie', 3, 0, 1),
	('carotool', 'outils carosserie', 4, 0, 1),
	('ceramic_coat', 'Ceramic Coat', 10, 0, 1),
	('chaee', 'Chaee', 10, 0, 1),
	('clip', 'Clip', -1, 0, 1),
	('clothe', 'Vaate', 40, 0, 1),
	('coca', 'Tokhm Kokayin', 150, 0, 1),
	('cocaine', 'Kokayin', 50, 0, 1),
	('coin', 'Coin', -1, 0, 1),
	('cookie_shekari', 'Cookie Shekari', 10, 0, 1),
	('copper', 'Kupari', 56, 0, 1),
	('crack', 'Crack', 25, 0, 1),
	('croissant_kareii', 'Croissant Kareii', 10, 0, 1),
	('cupcake', 'Cup Cake', 10, 0, 1),
	('cupcake_shokolati', 'Cupcake Shokolati', 10, 0, 1),
	('customcoupon', 'Coupon', -1, 0, 1),
	('cutted_wood', 'Pilkottu Puu', 20, 0, 1),
	('dabs', 'Dabs', 50, 0, 1),
	('daneghahve', 'Dane Ghahve', 30, 0, 1),
	('delester', 'Delester', -1, 0, 1),
	('diamond', 'Timantti', 50, 0, 1),
	('dooghbg', 'Doogh Bozorg', -1, 0, 1),
	('dooghg', 'Doogh Kuchak', -1, 0, 1),
	('drugtest', 'Test Mavad', 10, 0, 1),
	('eaglemeet', 'Eagle Meat', -1, 0, 1),
	('ebitenrol', 'Ebi Tenrol', -1, 0, 1),
	('eclip', 'Extended Clip', -1, 0, 1),
	('egg', 'Tokhm Morgh', 30, 0, 1),
	('energy_mix', 'Energy Mix', 10, 0, 1),
	('engine', 'Engine', -1, 0, 1),
	('engine1', 'Engine Scrap X1', -1, 0, 1),
	('engine2', 'Engine Scrap X2', -1, 0, 1),
	('engine3', 'Engine Scrap X3', -1, 0, 1),
	('engine4', 'Engine Scrap X4', -1, 0, 1),
	('engine5', 'Engine Scrap X5', -1, 0, 1),
	('engine6', 'Engine Scrap X6', -1, 0, 1),
	('ephedra', 'Ephedra', 100, 0, 1),
	('ephedrine', 'Ephedrine', 100, 0, 1),
	('eskenas', 'Eskenas', -1, 0, 1),
	('essence', 'PolttoÃ¶ljy', 24, 0, 1),
	('fabric', 'Kangas', 80, 0, 1),
	('fakepee', 'Fake Pee', 5, 0, 1),
	('fenjon', 'Fenjon', 30, 0, 1),
	('fenjonkasif', 'Fenjon Kasif', 30, 0, 1),
	('fish', 'Kala', 100, 0, 1),
	('fishingrod', 'Fishing Rod', -1, 0, 1),
	('fixkit', 'Kit rÃ©paration', 5, 0, 1),
	('fixtool', 'outils rÃ©paration', 6, 0, 1),
	('fountain', 'Fountain Firework', 3, 0, 1),
	('froyo_mango', 'Froyo Mango', 10, 0, 1),
	('fruit_punch', 'Fruit Punch', 10, 0, 1),
	('garlic_bread', 'Garlic Bread', 10, 0, 1),
	('gazbottle', 'bouteille de gaz', 11, 0, 1),
	('gazellemeet', 'Gazelle Meat', -1, 0, 1),
	('ghahve100', 'Ghahve 100', 10, 0, 1),
	('ghahve50', 'Ghahve 50', 10, 0, 1),
	('ghahve80', 'Ghahve 80', 10, 0, 1),
	('gold', 'Kulta', 21, 0, 1),
	('goshteaho', 'Goshte Aho', 20, 0, 1),
	('goshtecougar', 'Goshte Cougar', 20, 0, 1),
	('goshtecoyote', 'Goshte Coyote', 20, 0, 1),
	('goshtehusky', 'Goshte Husky', 20, 0, 1),
	('goshtekhargush', 'Goshte Khargush', 20, 0, 1),
	('goshteoghab', 'Goshte Oghab', 20, 0, 1),
	('goshtepig', 'Goshte Pig', 20, 0, 1),
	('goshterottweiler', 'Goshte Rottweiler', 20, 0, 1),
	('grip', 'Grip', -1, 0, 1),
	('headeaho', 'Heade Aho', 20, 0, 1),
	('headecougar', 'Heade Cougar', 20, 0, 1),
	('headecoyote', 'Heade Coyote', 20, 0, 1),
	('headehusky', 'Heade Husky', 20, 0, 1),
	('headekhargush', 'Heade Khargush', 20, 0, 1),
	('heademorgh', 'Heade Morgh', 20, 0, 1),
	('headeoghab', 'Heade Oghab', 20, 0, 1),
	('headepig', 'Heade Pig', 20, 0, 1),
	('headerottweiler', 'Heade Rottweiler', 20, 0, 1),
	('henmeat', 'Hen Meat', -1, 0, 1),
	('heroine', 'Heroine', 10, 0, 1),
	('hifi', 'HiFi', 1, 0, 1),
	('hotwire', 'Pich Goshti', -1, 0, 1),
	('hot_chocolate', 'Hot Chocolate', 10, 0, 1),
	('icecream_chocolate_cone', 'Icecream Chocolate Cone', 10, 0, 1),
	('icecream_sandwich', 'Icecream Sandwich', 10, 0, 1),
	('icecream_vanilla_cone', 'Icecream Vanilla Cone', 10, 0, 1),
	('ice_coffee_matcha', 'Ice Coffee Matcha', 10, 0, 1),
	('ice_tea_special', 'Ice Tea Special', 10, 0, 1),
	('interior_cleaner', 'Interior Cleaner Kit', 10, 0, 1),
	('iron', 'Rauta', 42, 0, 1),
	('joje', 'Joje', -1, 0, 1),
	('kabab', 'Kabab', -1, 0, 1),
	('kare', 'Kare', 30, 0, 1),
	('kase', 'Kase', 30, 0, 1),
	('kasekasif', 'Kase Kasif', 30, 0, 1),
	('keik_shokolat', 'Keik Shokolat', 10, 0, 1),
	('khame', 'Khame', 30, 0, 1),
	('khame_yakhi', 'Khame Yakhi', 30, 0, 1),
	('khamir_pizza', 'Khamir Pizza', 30, 0, 1),
	('khamir_shirini', 'Khamir Shirini', 30, 0, 1),
	('laptophack', 'Hacking Laptop', -1, 0, 1),
	('lasheaho', 'Lashe Aho', 20, 0, 1),
	('lashecougar', 'Lashe Cougar', 20, 0, 1),
	('lashecoyote', 'Lashe Coyote', 20, 0, 1),
	('lashehusky', 'Lashe Husky', 20, 0, 1),
	('lashekhargush', 'Lashe Khargush', 20, 0, 1),
	('lashemorgh', 'Lashe Morgh', -1, 0, 1),
	('lashemorgh.png', 'Lashe Morgh', 20, 0, 1),
	('lasheoghab', 'Lashe Oghab', 20, 0, 1),
	('lashepig', 'Lashe Pig', 20, 0, 1),
	('lasherottweiler', 'Lashe Rottweiler', 20, 0, 1),
	('latte', 'Latte', 10, 0, 1),
	('lighter', 'Lighter', -1, 0, 1),
	('limo', 'Limo', 30, 0, 1),
	('lockpick', 'Lockpick', -1, 0, 1),
	('lsd', 'LSD', -1, 0, 1),
	('maahi_khaam', 'Maahi Khaam', 30, 0, 1),
	('mahighezel', 'Mahi Ghezel', -1, 0, 1),
	('mahigolip', 'Mahi Golip', -1, 0, 1),
	('mahihamoor', 'Mahi Hamoor', -1, 0, 1),
	('marijuana', 'Marijuana', 250, 0, 1),
	('medikit', 'Medikit', 5, 0, 1),
	('meth', 'Meth', 25, 0, 1),
	('microfiber_cloth', 'Microfiber Cloth', 30, 0, 1),
	('milkshake', 'Milk Shake', 10, 0, 1),
	('milkshake_strawberry', 'Milkshake Strawberry', 10, 0, 1),
	('milk_shake_shokolati', 'Milk Shake Shokolati', 10, 0, 1),
	('miso_soup', 'Miso Soup', 10, 0, 1),
	('mive_mix', 'Mive Mix', 30, 0, 1),
	('mocktail_mojito', 'Virgin Mojito', 10, 0, 1),
	('mocktail_pinacolada', 'Virgin Pina Colada', 10, 0, 1),
	('mufchocolate', 'Mufchocolate', 10, 0, 1),
	('muffin_tamshak', 'Muffin Tamshak', 10, 0, 1),
	('mushroom', 'Mushroom', -1, 0, 1),
	('narcan', 'Narcan', 10, 0, 1),
	('net_cracker', 'Net Cracker', -1, 0, 1),
	('nodel', 'Nodel', 10, 0, 1),
	('nodel_kham', 'Nodel Kham', 30, 0, 1),
	('non_baget', 'Non Baget', 10, 0, 1),
	('noodles', 'Noodles', 10, 0, 1),
	('nori', 'Nori', 30, 0, 1),
	('noshab', 'Noshabe', -1, 0, 1),
	('nutela', 'Nutela', 10, 0, 1),
	('opium', 'Teryak', 50, 0, 1),
	('oreo', 'Oreo', 30, 0, 1),
	('packaged_chicken', 'Kananfilee', 100, 0, 1),
	('packaged_plank', 'Paketoitu Lankku', 100, 0, 1),
	('painkiller', 'Painkiller', 10, 0, 1),
	('panir_pizza', 'Panir Pizza', 30, 0, 1),
	('pankik', 'Pankik', 10, 0, 1),
	('pankik_nutella', 'Pankik Nutella', 10, 0, 1),
	('pankik_oreo', 'Pankik Oreo', 10, 0, 1),
	('pcp', 'PCP', 25, 0, 1),
	('petrol', 'Ã–ljy', 24, 0, 1),
	('petrol_raffin', 'Prosessoitu Ã–ljy', 24, 0, 1),
	('phone', 'Goshi', -1, 0, 1),
	('pizzama', 'Pizza Ma', -1, 0, 1),
	('pizzamo', 'Pizza Mo', -1, 0, 1),
	('pizza_bbq_chicken', 'Pizza BBQ Chicken', 10, 0, 1),
	('pizza_margherita', 'Pizza Margherita', 10, 0, 1),
	('pizza_mushroom', 'Pizza Mushroom', 10, 0, 1),
	('pizza_pepperoni', 'Pizza Pepperoni', 10, 0, 1),
	('podrcacao', 'Podr Cacao', 30, 0, 1),
	('poppy', 'KhashKhaash', 25, 0, 1),
	('posteaho', 'Poste Aho', 20, 0, 1),
	('postecougar', 'Poste Cougar', 20, 0, 1),
	('postecoyote', 'Poste Coyote', 20, 0, 1),
	('postehusky', 'Poste Husky', 20, 0, 1),
	('postekhargush', 'Poste Khargush', 20, 0, 1),
	('postepig', 'Poste Pig', 20, 0, 1),
	('poster', 'Poster', -1, 0, 1),
	('posterottweiler', 'Poste Rottweiler', 20, 0, 1),
	('powdr_matcha', 'Powdr Matcha', 30, 0, 1),
	('premium_wax', 'Premium Wax', 10, 0, 1),
	('rabbitmeat', 'Rabbit Meat', -1, 0, 1),
	('radio', 'Radio', -1, 0, 1),
	('rim_polish', 'Rim Polish', 10, 0, 1),
	('roll_darchin', 'Roll Darchin', 10, 0, 1),
	('scope', 'Scope', -1, 0, 1),
	('sf', 'SF', -1, 0, 1),
	('sh', 'SH', -1, 0, 1),
	('shahkelid', 'Shah Kelid', -1, 0, 1),
	('shekar', 'Shekar', 30, 0, 1),
	('shir', 'Shir', 30, 0, 1),
	('shirini_khamei', 'Shirini Khamei', 10, 0, 1),
	('shokolat', 'Shokolat', 10, 0, 1),
	('shotburst', 'Shotburst Firework', 3, 0, 1),
	('sianor', 'Sianor', -1, 0, 1),
	('sibp', 'Sib Zamini', -1, 0, 1),
	('silencer', 'Silencer', -1, 0, 1),
	('slaughtered_chicken', 'Teurastettu kana', 20, 0, 1),
	('sm', 'SM', -1, 0, 1),
	('soap_foam', 'Soap Foam', 30, 0, 1),
	('soda_lime', 'Soda Lime', 10, 0, 1),
	('soda_water', 'Soda Water', 30, 0, 1),
	('sos_gojeh', 'Sos Gojeh', 30, 0, 1),
	('ss', 'SS', -1, 0, 1),
	('starburst', 'Starburst Firework', 3, 0, 1),
	('stone', 'Kivi', 7, 0, 1),
	('sundae_caramel', 'Sundae Caramel', 10, 0, 1),
	('suop', 'Suop', 10, 0, 1),
	('sushi_california', 'Sushi California', 10, 0, 1),
	('sushi_dragon_roll', 'Sushi Dragon Roll', 10, 0, 1),
	('sushi_salmon_nigiri', 'Sushi Salmon Nigiri', 10, 0, 1),
	('sushi_spicy_tuna', 'Sushi Spicy Tuna', 10, 0, 1),
	('sushi_veggie_roll', 'Sushi Veggie Roll', 10, 0, 1),
	('tamshak', 'Tamshak', 30, 0, 1),
	('tequila', 'Tequila', 10, 0, 1),
	('tiramisuye_toot_farangi', 'Tiramisuye TotFarangi', 10, 0, 1),
	('tire_shine', 'Tire Shine', 10, 0, 1),
	('totfarangi', 'Tot Farangi', 30, 0, 1),
	('trailburst', 'Trailburst Firework', 3, 0, 1),
	('unagieelroll', 'Unagi Eel Roll', -1, 0, 1),
	('vafel_nutella', 'Vafel Nutella', 10, 0, 1),
	('vanil', 'Vanil', 30, 0, 1),
	('vodka', 'Vodka', 10, 0, 1),
	('washed_stone', 'Puhdistettu Kivi', 7, 0, 1),
	('water', 'Water', -1, 0, 1),
	('whiskey', 'Whiskey', 10, 0, 1),
	('whool', 'Wolle', 40, 0, 1),
	('wood', 'Puu', 20, 0, 1),
	('wool', 'Villa', 40, 0, 1),
	('xpbank', 'XP Bank Card', -1, 0, 1),
	('xpshop', 'XP Shop Card', -1, 0, 1),
	('yakh', 'Yakh', 30, 0, 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
