

local Suggestions = {
    { '/911', 'Darkhast-e emdad-e foori baraye pezeshk/ambulance' },
    { '/SitAnyWhere', 'Neshastan rooye har noghte-i az zamin/mohit' },
    { '/_SynSit_Lean', 'Tekye dadan be divar (halat-e lam dadan)' },
    { '/acceptrob', 'Baz kardan-e menu-ye robbery-haye faal baraye accept kardan' },
    { '/accp', 'Ghabul kardan-e yek taghib-o-goriz (Pursuit) faal tavassot-e police' },
    { '/achievements', 'Baz/baste kardan-e menu-ye dastavardha (Achievements/Skill)' },
    { '/ad_weazel', 'Modiriat-e tablighat-e Weazel News: /ad_weazel [shomare-ye tabligh] [action]' },
    { '/admins', 'Namayesh-e list-e admin-haye online va vaziat-e on-duty/off-duty-e unha' },
    { '/ads', 'Namayesh-e list-e tablighat-e faal-e Weazel News' },
    { '/afk', 'Pasokh be soal-e riazi-ye zedd-AFK: /afk [javab-e adad]' },
    { '/agent', 'Baz kardan-e menu-ye amaliyat-e FBI/CIA (spectate, otagh-e bazjuyi, jostoju-ye shomare)' },
    { '/agentmsg', 'Ersal-e payam be fard-e spectate shode (FBI/CIA)' },
    { '/ajoin', 'Chek kardan-e vaziat-e zendan-e feli-ye player hangam-e entekhab-e shoghl' },
    { '/assign', 'Assign kardan-e yek darkhast-e dispatch be khod (police/emdad ba HR)' },
    { '/badge', 'Neshan dadan-e animation-e neshan (badge) shoghli be atrafian' },
    { '/bc', 'Ersal-e darkhast-e Backup be hame-ye ozv-haye DOJ/LE' },
    { '/bmic', 'Roshan/khamoosh kardan-e microphone-e boom-e dorbin-e khabarnegar-e Weazel' },
    { '/boombox_openmenu', 'Baz kardan-e menu-ye boombox' },
    { '/boombox_stop', 'Khamoosh kardan-e foori-ye boombox' },
    { '/cam', 'Roshan/khamoosh kardan-e dorbin-e khabari-ye Weazel News' },
    { '/cancelprogress', 'Laghv-e navar-e pishraft (progress bar) feli' },
    { '/carrymdd', 'Ersal-e darkhast-e haml-e bimar be yek emdadgar: /carrymdd [id]' },
    { '/cctv', 'Taviz/baz kardan-e dorbin-e madar-baste: /cctv [shomare-ye dorbin]' },
    { '/checkfreq', 'Darkhast/taeed-e namayesh-e frequency-ye radio-ye yek player: /checkfreq [id|accept]' },
    { '/checktime', 'Namayesh-e zaman-e baghimande-ye habs-e yek player: /checktime [id]' },
    { '/close', 'Bastan-e hame-ye menu-haye baz-e ESX va kharej kardan-e focus-e NUI' },
    { '/closespec', 'Quit kardan-e spectate-e faal (FBI/CIA)' },
    { '/combat', 'Baz kardan-e panel-e zedd-tarkib-code (Anti-CL) baraye gozaresh' },
    { '/coords', 'Roshan/khamoosh kardan-e namayesh-e mokhtasat rooye safhe' },
    { '/crecord', 'Shoroo-e zabt-e abr-video (Rockstar Editor - Clip)' },
    { '/cresp', 'Cancel kardan-e response-e panic-e faal-e shoma' },
    { '/cross', 'Faal kardan-e neshangar (Crosshair) sefareshi' },
    { '/crosse', 'Baz kardan-e halat-e virayesh-e neshangar (Crosshair)' },
    { '/crossr', 'Reset kardan-e neshangar (Crosshair) be halat-e pish-farz' },
    { '/custom', 'Baz kardan-e menu-ye shakhsi-sazi-ye mashin dar tamirgah (mechanic grade 7+)' },
    { '/cycleproximity', 'Taviz-e halat-e range-e seda-ye radio-ye nazdik (Proximity Voice)' },
    { '/dep', 'Ersal-e payam-e radiovi be kol-e department (sazman)-e khodet' },
    { '/dfs', '[Paintball] Laghv-e halat-e scope/zoom-e aslahe' },
    { '/documents_openmenu', 'Baz kardan-e menu-ye asli-ye madarek-e rasmi' },
    { '/doj', 'Baz kardan-e menu-ye DOJ (parvande-ha, hokm-ha, ghanoon-name, sabeghe-ye kayfari va bishtar)' },
    { '/editor', 'Baz kardan-e Rockstar Video Editor' },
    { '/f', 'Ersal-e payam-e radiovi-e frequency be hamkaran-e ham-sazman' },
    { '/fcw', 'Bastan-e chatroom-e bazjuyi-e faal (FBI/CIA)' },
    { '/findnumber', 'Peyda kardan-e saheb-e yek shomare-ye telephone (DOJ/LE): /findnumber [shomare]' },
    { '/fixme', 'Fix kardan-e bug-e gir kardan-e aslahe rooye kamar (Holster)' },
    { '/flist', 'Namayesh-e list-e player-haye on-duty/off-duty-e shoghl-e khodet dar chat' },
    { '/fow', 'Baz kardan-e chatroom-e bazjuyi ba yek player (FBI/CIA): /fow [id]' },
    { '/fps', 'Baz kardan-e menu-ye FPS booster (performance-e graphic)' },
    { '/fps2', 'Baz kardan-e noskhe-ye dovom-e menu-ye FPS booster' },
    { '/fpsmenu', 'Baz kardan-e menu-ye tanzimat-e FPS (Reset/Low/Medium)' },
    { '/fw', 'Ersal-e payam dar chatroom-e bazjuyi-e faal (FBI/CIA)' },
    { '/g', 'Ersal-e payam dar chat-e khosoosi-ye gang-e khodet: /g [matn]' },
    { '/gangs', 'Roshan/khamoosh kardan-e blip-haye ghalamro-e gang-ha rooye naghshe' },
    { '/getclass', 'Namayesh-e class va esm-e mashini ke savaresh hasti ya negahesh mikoni' },
    { '/givekey', 'Dadan-e kelid-e mashin be yek player-e nazdik: /givekey [id]' },
    { '/glist', 'Namayesh-e list-e aza-ye gang-e khodet dar chat' },
    { '/hs', 'Roshan/khamoosh kardan-e seda-ye barkhord-e zarbe (Hit Sound)' },
    { '/inventory_toggle', 'Baz/baste kardan-e inventory' },
    { '/invite', 'Davat-e yek player be department (police/emdad ba grade-e kafi)' },
    { '/jail', 'Zendani kardan-e yek player: /jail [id] [daghighe] [dalil]' },
    { '/jerahat', 'Barrasi va tashkhis-e jerahat-e nazdik-tarin player (shoghl-e emdad)' },
    { '/jailpd', 'Zendani kardan-e edari ba flag-e cell-e vaghei-ye PD: /jailpd [id] [daghighe] [dalil]' },
    { '/joblist', 'Namayesh-e list-e player-haye online be tafkik-e shoghl (niazmand-e permission)' },
    { '/keys', 'Refresh/barrasi-e mojaddad-e kelid-haye mashin-e mojood dar inventory' },
    { '/law', 'Baz kardan-e ghanoon-name baraye police/sheriff/mt va sodoor-e jarime' },
    { '/lockdoor', 'Ghofl/baz kardan-e dar-e nazdik (ba pin dar soorat-e niaz)' },
    { '/me', 'Namayesh-e yek matn-e action bala-ye sar-e character (Roleplay /me)' },
    { '/menu', 'Baz kardan-e menu-ye level/quest/dastavard (Unique_LevelQuest)' },
    { '/mic', 'Roshan/khamoosh kardan-e microphone-e dorbin-e khabari-ye Weazel' },
    { '/mydocuments', 'Namayesh-e list-e madarek-e rasmi-ye sader-shode baraye khodet' },
    { '/myxp', 'Namayesh-e XP va level-e feli-ye khodet dar chat' },
    { '/nearby', 'Didan/be-eshterak-gozari-ye emotion ba nazdik-tarin player' },
    { '/neon', 'Roshan/khamoosh kardan-e neon-e mashin: /neon [on|off]' },
    { '/news', 'Sabt-e yek agahi-e matni-ye Weazel News: /news [matn]' },
    { '/newstime', 'Sabt-e yek agahi-e timer-dar-e Weazel News: /newstime [bar-e tekrar] [saniye] [matn]' },
    { '/oeditor', 'Baz kardan-e Rockstar Object Editor' },
    { '/ox_lib', 'Baz kardan-e panel-e tanzimat-e ox_lib (seda-ye notification, moghe-iat va...)' },
    { '/pbmsd', '[Paintball] Scroll be payin beyn-e spectate-e ham-timi-ha' },
    { '/pbmsu', '[Paintball] Scroll be bala beyn-e spectate-e ham-timi-ha' },
    { '/pc', 'Ersal-e darkhast-e Panic (halat-e khatar) be hame-ye ozv-haye DOJ/LE' },
    { '/phone', 'Baz kardan-e mobile' },
    { '/r', 'Ersal-e payam-e radiovi rooye frequency-ye feli: /r [matn]' },
    { '/record', 'Shoroo-e zabt-e video-ye Rockstar Editor' },
    { '/report', 'Ersal-e yek ticket-e gozaresh (Report)-e jadid be admin-ha' },
    { '/resp', 'Pasokh be yek darkhast-e Panic/Backup: /resp [id]' },
    { '/sl', 'Namayesh-e gavahiname-ye yek player-e nazdik: /sl [id]' },
    { '/solitary', 'Enteghal-e yek zendani be cell-e enferadi: /solitary [id] [daghighe] [dalil]' },
    { '/sr', 'Ersal-e payam-e radiovi-e sazmani-ye sarasari (shoghl-haye khas ba grade 4+)' },
    { '/srecord', 'Tavaghof-e zabt-e video-ye Rockstar Editor' },
    { '/streamermode', 'Roshan/khamoosh kardan-e halat-e streamer (ghat-e seda-ye pakhsh-shavande-ye xsound)' },
    { '/surface', 'Namayesh-e noe sath-e jadde zir-e charkh-haye mashin-e feli' },
    { '/tabligh', 'Sabt-e yek tabligh-e matni-ye Weazel ba pardakht-e hazine az bank' },
    { '/timeplay', 'Namayesh-e saat-e bazi (Time Played)-e khodet ya yek player: /timeplay [id]' },
    { '/tirefix', 'Hazf-e prop-e lastik dar hal-e tamir (fix-e bug-e chasbidan)' },
    { '/togglebelt', 'Bastan/baz kardan-e kamarband-e imeni' },
    { '/togglegps', 'Roshan/khamoosh kardan-e naghshe-ye bozorg (Bigmap/radar)' },
    { '/togglehud', 'Namayesh/makhfi kardan-e darsad-e health va armor rooye HUD' },
    { '/uniquegarage_carlock_toggle', 'Ghofl/baz kardan-e dar-e mashin (savar ya nazdik be an)' },
    { '/unit', 'Baz kardan-e menu-ye modiriat-e vahed-e radiovi (sakht/join/leave/rename/disband)' },
    { '/unjail', 'Azad kardan-e yek player az zendan: /unjail [id] (grade 4+)' },
    { '/vehcontrol', 'Baz kardan-e menu-ye control-e mashin (ghofl, shishe, cheragh va...)' },
    { '/vehcontrolclose', 'Bastan-e menu-ye control-e mashin' },
    { '/weapback', 'Baz kardan-e menu-ye haml-e aslahe rooye posht (mahdood be nazdiki-ye boss-e gang)' },
}

CreateThread(function()
    for _, s in ipairs(Suggestions) do
        TriggerEvent('chat:addSuggestion', s[1], s[2])
    end
end)
