ReportLan = {}

ReportLan.submitReport = 'report shoma ersal shod lotfan ta taiid shodan sabor bashid'
ReportLan.reportLimit = "shoma dar hale hazer yek report baz darid lotdan sabr konid"
ReportLan.acceptByauthor = "in report tavasot yek dar dige accept shode"
ReportLan.Accept = "report accept shod"
ReportLan.Acceptuser = "report shoma taiid shod ba /report mitonid ba admin dar ertebat bashid"
ReportLan.cantaccept = "Shoma nemitavid Report Khod Ra Accept Konid"
ReportLan.ErrToaccept = "error to accept Report"
ReportLan.CantAfterAccep = "shoma nemitavnid in report ro accept konid"
ReportLan.deleteReport = "report hazf shod"
ReportLan.cantdel = 'shoma nemitavnid in report ro hazf konid'
ReportLan.err = "server error"
ReportLan.notAccess = "shoma be in option dastresi nadarid"
ReportLan.AdminReportLimit = "shoma yek report accept shode darid "
ReportLan.CantAfterAcceptDelete = "shoma nemitvanid report ra bebandid"
ReportLan.closed = "Shoma Ba movaghiat In Report Ro Be Etmam Resondi"
ReportLan.reportnotfound = "report peyda nashod"
ReportLan.adminxpAdd = "Shoma XP Admini Daryaft Kardid"
ReportLan.notOnline = "player online nist"
ReportLan.adminGiveCar = "admin car be player dade shode"
ReportLan.playerGiveCar = 'shoma tavasod admin vasile naghlie daryaft kardid'
ReportLan.AdminRevive = 'shoma player ra ravive kardid'
ReportLan.playerRevive = 'shoma tavasot admin revive shodid'
ReportLan.AdminTeleport = "shoma be moghiat player TP shodi"
ReportLan.UserAdminTeleport = "admin be moghiat shoma Tp Shod"
ReportLan.tankstofeedback = "Mamnon Be khter Sabt nazar"
ReportLan.AdminAlertNewMessage  = "شما یک پیام جدید در تیکت دارید لطفا هرچه سریع تر پاسخگو باشید"
ReportLan.UserAlertNewMessage  = "شما از طرف ادمین در ریپورت یک پیام دریافت کردید"
ReportLan.newReprot ="یک ریپورت جدید ثبت شده"