-- Generated from esx_adminmenu weapon list: { spawn name, label }
WeaponCatalog = {
  { category = 'Melee', items = {
    { 'weapon_unarmed', 'Fists' },
    { 'weapon_dagger', 'Dagger' },
    { 'weapon_bat', 'Bat' },
    { 'weapon_bottle', 'Broken Bottle' },
    { 'weapon_crowbar', 'Crowbar' },
    { 'weapon_flashlight', 'Flashlight' },
    { 'weapon_golfclub', 'Golfclub' },
    { 'weapon_hammer', 'Hammer' },
    { 'weapon_hatchet', 'Hatchet' },
    { 'weapon_knuckle', 'Knuckle' },
    { 'weapon_knife', 'Knife' },
    { 'weapon_machete', 'Machete' },
    { 'weapon_switchblade', 'Switchblade' },
    { 'weapon_nightstick', 'Nightstick' },
    { 'weapon_wrench', 'Wrench' },
    { 'weapon_battleaxe', 'Battle Axe' },
    { 'weapon_poolcue', 'Poolcue' },
    { 'weapon_briefcase', 'Briefcase' },
    { 'weapon_briefcase_02', 'Briefcase' },
    { 'weapon_garbagebag', 'Garbage Bag' },
    { 'weapon_handcuffs', 'Handcuffs' },
    { 'weapon_bread', 'Baquette' },
    { 'weapon_stone_hatchet', 'Stone Hatchet' },
    { 'weapon_candycane', 'Candy Cane' },
  } },
  { category = 'Pistol', items = {
    { 'weapon_pistol', 'Pistol' },
    { 'weapon_pistol_mk2', 'Pistol Mk2' },
    { 'weapon_combatpistol', 'Combat Pistol' },
    { 'weapon_appistol', 'AP Pistol' },
    { 'weapon_stungun', 'Taser' },
    { 'weapon_pistol50', 'Pistol .50 Cal' },
    { 'weapon_snspistol', 'SNS Pistol' },
    { 'weapon_snspistol_mk2', 'SNS Pistol MK2' },
    { 'weapon_heavypistol', 'Heavy Pistol' },
    { 'weapon_vintagepistol', 'Vintage Pistol' },
    { 'weapon_flaregun', 'Flare Gun' },
    { 'weapon_marksmanpistol', 'Marksman Pistol' },
    { 'weapon_revolver', 'Revolver' },
    { 'weapon_revolver_mk2', 'Revolver MK2' },
    { 'weapon_doubleaction', 'Double Action Revolver' },
    { 'weapon_raypistol', 'Ray Pistol' },
    { 'weapon_ceramicpistol', 'Ceramic Pistol' },
    { 'weapon_navyrevolver', 'Navy Revolver' },
    { 'weapon_gadgetpistol', 'Gadget Pistol' },
    { 'weapon_stungun_mp', 'Taser' },
    { 'weapon_pistolxm3', 'Pistol XM3' },
  } },
  { category = 'Submachine Gun', items = {
    { 'weapon_microsmg', 'Micro SMG' },
    { 'weapon_smg', 'SMG' },
    { 'weapon_smg_mk2', 'SMG MK2' },
    { 'weapon_assaultsmg', 'Assault SMG' },
    { 'weapon_combatpdw', 'Combat PDW' },
    { 'weapon_machinepistol', 'Tec-9' },
    { 'weapon_minismg', 'Mini SMG' },
    { 'weapon_raycarbine', 'Raycarbine' },
  } },
  { category = 'Shotgun', items = {
    { 'weapon_pumpshotgun', 'Pump Shotgun' },
    { 'weapon_pumpshotgun_mk2', 'Pump Shotgun MK2' },
    { 'weapon_sawnoffshotgun', 'Sawn-off Shotgun' },
    { 'weapon_assaultshotgun', 'Assault Shotgun' },
    { 'weapon_bullpupshotgun', 'Bullpup Shotgun' },
    { 'weapon_musket', 'Musket' },
    { 'weapon_heavyshotgun', 'Heavy Shotgun' },
    { 'weapon_dbshotgun', 'Double-barrel Shotgun' },
    { 'weapon_autoshotgun', 'Auto Shotgun' },
    { 'weapon_combatshotgun', 'Combat Shotgun' },
  } },
  { category = 'Assault Rifle', items = {
    { 'weapon_assaultrifle', 'Assault Rifle' },
    { 'weapon_assaultrifle_mk2', 'Assault Rifle MK2' },
    { 'weapon_carbinerifle', 'Carbine Rifle' },
    { 'weapon_carbinerifle_mk2', 'Carbine Rifle MK2' },
    { 'weapon_advancedrifle', 'Advanced Rifle' },
    { 'weapon_specialcarbine', 'Special Carbine' },
    { 'weapon_specialcarbine_mk2', 'Specialcarbine MK2' },
    { 'weapon_bullpuprifle', 'Bullpup Rifle' },
    { 'weapon_bullpuprifle_mk2', 'Bull Puprifle MK2' },
    { 'weapon_compactrifle', 'Compact Rifle' },
    { 'weapon_militaryrifle', 'Military Rifle' },
    { 'weapon_heavyrifle', 'Heavy Rifle' },
  } },
  { category = 'Light Machine Gun', items = {
    { 'weapon_mg', 'Machinegun' },
    { 'weapon_combatmg', 'Combat MG' },
    { 'weapon_combatmg_mk2', 'Combat MG MK2' },
    { 'weapon_gusenberg', 'Thompson SMG' },
  } },
  { category = 'Sniper Rifle', items = {
    { 'weapon_sniperrifle', 'Sniper Rifle' },
    { 'weapon_heavysniper', 'Heavy Sniper' },
    { 'weapon_heavysniper_mk2', 'Heavysniper MK2' },
    { 'weapon_marksmanrifle', 'Marksman Rifle' },
    { 'weapon_marksmanrifle_mk2', 'Marksman Rifle MK2' },
    { 'weapon_remotesniper', 'Remote Sniper' },
  } },
  { category = 'Heavy Weapons', items = {
    { 'weapon_rpg', 'RPG' },
    { 'weapon_grenadelauncher', 'Grenade Launcher' },
    { 'weapon_grenadelauncher_smoke', 'Smoke Grenade Launcher' },
    { 'weapon_minigun', 'Minigun' },
    { 'weapon_firework', 'Firework Launcher' },
    { 'weapon_railgun', 'Railgun' },
    { 'weapon_railgunxm3', 'Railgun XM3' },
    { 'weapon_hominglauncher', 'Homing Launcher' },
    { 'weapon_compactlauncher', 'Compact Launcher' },
    { 'weapon_rayminigun', 'Ray Minigun' },
    { 'weapon_emplauncher', 'EMP Launcher' },
  } },
  { category = 'Throwable', items = {
    { 'weapon_grenade', 'Grenade' },
    { 'weapon_bzgas', 'BZ Gas' },
    { 'weapon_molotov', 'Molotov' },
    { 'weapon_stickybomb', 'C4' },
    { 'weapon_proxmine', 'Proxmine Grenade' },
    { 'weapon_snowball', 'Snowball' },
    { 'weapon_pipebomb', 'Pipe Bomb' },
    { 'weapon_ball', 'Ball' },
    { 'weapon_smokegrenade', 'Smoke Grenade' },
    { 'weapon_flare', 'Flare pistol' },
  } },
  { category = 'Miscellaneous', items = {
    { 'weapon_petrolcan', 'Petrol Can' },
    { 'gadget_parachute', 'Parachute' },
    { 'weapon_fireextinguisher', 'Fire Extinguisher' },
    { 'weapon_hazardcan', 'Hazardcan' },
  } },
}
